import { NextResponse } from 'next/server'
import { db } from '@/lib/db'

const CATEGORIES = [
  { slug: 'queijos', namePt: 'Queijos', nameEn: 'Cheeses', nameFr: 'Fromages', nameDe: 'Käse', sortOrder: 1 },
  { slug: 'manteigas', namePt: 'Manteigas', nameEn: 'Butters', nameFr: 'Beurres', nameDe: 'Butter', sortOrder: 2 },
  { slug: 'conservas', namePt: 'Conservas', nameEn: 'Preserves', nameFr: 'Conserves', nameDe: 'Konserven', sortOrder: 3 },
  { slug: 'vinhos', namePt: 'Vinhos', nameEn: 'Wines', nameFr: 'Vins', nameDe: 'Weine', sortOrder: 4 },
  { slug: 'licores', namePt: 'Licores', nameEn: 'Liqueurs', nameFr: 'Liqueurs', nameDe: 'Liköre', sortOrder: 5 },
  { slug: 'cha', namePt: 'Chás', nameEn: 'Teas', nameFr: 'Thés', nameDe: 'Tees', sortOrder: 6 },
  { slug: 'pastelaria', namePt: 'Pastelaria & Bolos', nameEn: 'Pastry & Cakes', nameFr: 'Pâtisserie', nameDe: 'Gebäck', sortOrder: 7 },
  { slug: 'compotas', namePt: 'Compotas & Mel', nameEn: 'Jams & Honey', nameFr: 'Confitures & Miel', nameDe: 'Marmeladen & Honig', sortOrder: 8 },
  { slug: 'pimentas', namePt: 'Pimentas & Especiarias', nameEn: 'Peppers & Spices', nameFr: 'Poivres & Épices', nameDe: 'Pfeffer & Gewürze', sortOrder: 9 },
  { slug: 'bebidas', namePt: 'Bebidas', nameEn: 'Beverages', nameFr: 'Boissons', nameDe: 'Getränke', sortOrder: 10 },
  { slug: 'charcutaria', namePt: 'Charcutaria', nameEn: 'Charcuterie', nameFr: 'Charcuterie', nameDe: 'Wurstwaren', sortOrder: 11 },
  { slug: 'outros', namePt: 'Outros Produtos', nameEn: 'Other Products', nameFr: 'Autres Produits', nameDe: 'Andere Produkte', sortOrder: 12 },
]

const PRODUCTS = [
  // QUEIJOS
  {
    sku: 'QSJ-001',
    namePt: 'Queijo São Jorge DOP Curado 500g',
    nameEn: 'São Jorge DOP Aged Cheese 500g',
    nameFr: 'Fromage São Jorge DOP Affiné 500g',
    nameDe: 'São Jorge DOP Gereifter Käse 500g',
    descriptionPt: 'O Queijo São Jorge DOP é um dos mais emblemáticos queijos portugueses, produzido exclusivamente na Ilha de São Jorge. Com textura firme e sabor intenso e picante, é curado durante mínimo de 3 meses em caves naturais. Ideal para tábuas de queijos, acompanhado de vinho do Pico.',
    descriptionEn: 'São Jorge DOP Cheese is one of Portugal\'s most iconic cheeses, produced exclusively on São Jorge Island. With a firm texture and intense, spicy flavor, it is aged for a minimum of 3 months in natural cellars. Perfect for cheese boards, paired with Pico wine.',
    price: 14.50,
    stock: 50,
    categorySlug: 'queijos',
    origin: 'São Jorge',
    featured: true,
    tags: ['queijo', 'dop', 'sao-jorge', 'curado'],
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&q=80',
  },
  {
    sku: 'QSJ-002',
    namePt: 'Queijo São Jorge DOP Semi-Curado 500g',
    nameEn: 'São Jorge DOP Semi-Aged Cheese 500g',
    nameFr: 'Fromage São Jorge DOP Demi-Affiné 500g',
    nameDe: 'São Jorge DOP Halbgereifter Käse 500g',
    descriptionPt: 'Queijo São Jorge DOP com cura intermédia, apresentando uma textura mais suave e sabor menos intenso que o curado. Perfeito para quem aprecia queijos de pasta semi-dura com notas lácteas e ligeiramente picantes.',
    descriptionEn: 'São Jorge DOP cheese with intermediate aging, presenting a softer texture and less intense flavor than the aged version. Perfect for those who appreciate semi-hard cheeses with milky and slightly spicy notes.',
    price: 12.75,
    stock: 40,
    categorySlug: 'queijos',
    origin: 'São Jorge',
    featured: false,
    tags: ['queijo', 'dop', 'sao-jorge', 'semi-curado'],
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800&q=80',
  },
  {
    sku: 'QFH-001',
    namePt: 'Queijo Morro do Faial Curado Pasta Mole 450g',
    nameEn: 'Faial Morro Soft Aged Cheese 450g',
    nameFr: 'Fromage Morro du Faial Affiné Pâte Molle 450g',
    nameDe: 'Faial Morro Weichkäse Gereift 450g',
    descriptionPt: 'Queijo artesanal da Ilha do Faial, produzido pela marca O Morro. De pasta mole e curado, apresenta uma crosta natural e interior cremoso com sabor suave e ligeiramente ácido. Uma raridade gastronómica dos Açores.',
    descriptionEn: 'Artisan cheese from Faial Island, produced by O Morro brand. Soft paste and aged, it has a natural rind and creamy interior with a mild, slightly acidic flavor. A gastronomic rarity from the Azores.',
    price: 9.75,
    stock: 30,
    categorySlug: 'queijos',
    origin: 'Faial',
    featured: true,
    tags: ['queijo', 'faial', 'mole', 'artesanal'],
    imageUrl: 'https://images.unsplash.com/photo-1599043513900-ed6fe01d3833?w=800&q=80',
  },
  {
    sku: 'QGR-001',
    namePt: 'Queijo da Graciosa Fresco 400g',
    nameEn: 'Graciosa Fresh Cheese 400g',
    nameFr: 'Fromage Frais de Graciosa 400g',
    nameDe: 'Graciosa Frischkäse 400g',
    descriptionPt: 'Queijo fresco da Ilha Graciosa, produzido com leite de vaca das pastagens naturais da ilha. Textura suave e cremosa, ideal para consumo imediato ou em receitas tradicionais açorianas.',
    descriptionEn: 'Fresh cheese from Graciosa Island, made with cow\'s milk from the island\'s natural pastures. Soft and creamy texture, ideal for immediate consumption or in traditional Azorean recipes.',
    price: 7.50,
    stock: 25,
    categorySlug: 'queijos',
    origin: 'Graciosa',
    featured: false,
    tags: ['queijo', 'graciosa', 'fresco'],
    imageUrl: 'https://images.unsplash.com/photo-1573246123716-6b1782bfc499?w=800&q=80',
  },
  // MANTEIGAS
  {
    sku: 'MAN-001',
    namePt: 'Manteiga dos Açores com Sal 250g',
    nameEn: 'Azores Salted Butter 250g',
    nameFr: 'Beurre des Açores Salé 250g',
    nameDe: 'Azoren Gesalzene Butter 250g',
    descriptionPt: 'Manteiga cremosa produzida com leite das pastagens naturais dos Açores. Rica em ómega-3 e com sabor intenso e autêntico. Produzida pela Finançor Agro-Alimentar, líder nos laticínios açorianos.',
    descriptionEn: 'Creamy butter made from milk from the Azores\' natural pastures. Rich in omega-3 with an intense and authentic flavor. Produced by Finançor Agro-Alimentar, leader in Azorean dairy products.',
    price: 4.25,
    stock: 80,
    categorySlug: 'manteigas',
    origin: 'São Miguel',
    featured: true,
    tags: ['manteiga', 'lacticinios', 'sao-miguel'],
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=800&q=80',
  },
  {
    sku: 'MAN-002',
    namePt: 'AzorGhee Manteiga Clarificada 300g',
    nameEn: 'AzorGhee Clarified Butter 300g',
    nameFr: 'AzorGhee Beurre Clarifié 300g',
    nameDe: 'AzorGhee Geklärte Butter 300g',
    descriptionPt: 'Ghee artesanal produzido com manteiga dos Açores, clarificada lentamente para remover a lactose e a caseína. Ideal para cozinhar a altas temperaturas, com sabor de avelã e aroma rico. Produzido na Ilha Terceira.',
    descriptionEn: 'Artisan ghee made with Azores butter, slowly clarified to remove lactose and casein. Ideal for high-temperature cooking, with a hazelnut flavor and rich aroma. Produced on Terceira Island.',
    price: 12.85,
    stock: 35,
    categorySlug: 'manteigas',
    origin: 'Terceira',
    featured: true,
    tags: ['manteiga', 'ghee', 'terceira', 'lacticinios'],
    imageUrl: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&q=80',
  },
  // CONSERVAS
  {
    sku: 'CON-001',
    namePt: 'Atum dos Açores em Azeite 120g',
    nameEn: 'Azores Tuna in Olive Oil 120g',
    nameFr: 'Thon des Açores à l\'Huile d\'Olive 120g',
    nameDe: 'Azoren Thunfisch in Olivenöl 120g',
    descriptionPt: 'Atum do Atlântico Norte pescado de forma sustentável nos Açores, conservado em azeite virgem extra. Carne firme e saborosa, ideal para saladas, tostas ou consumo direto. Produto da Indústria Conserveira dos Açores.',
    descriptionEn: 'North Atlantic tuna sustainably caught in the Azores, preserved in extra virgin olive oil. Firm and flavorful meat, ideal for salads, toasts or direct consumption.',
    price: 5.50,
    stock: 100,
    categorySlug: 'conservas',
    origin: 'São Miguel',
    featured: true,
    tags: ['conservas', 'atum', 'peixe', 'atlantico'],
    imageUrl: 'https://images.unsplash.com/photo-1534482421-64566f976cfa?w=800&q=80',
  },
  {
    sku: 'CON-002',
    namePt: 'Polvo dos Açores em Azeite 120g',
    nameEn: 'Azores Octopus in Olive Oil 120g',
    nameFr: 'Poulpe des Açores à l\'Huile d\'Olive 120g',
    nameDe: 'Azoren Oktopus in Olivenöl 120g',
    descriptionPt: 'Polvo do Atlântico capturado nos Açores, cozinhado e conservado em azeite virgem extra com alho e louro. Textura tenra e sabor intenso do mar. Perfeito para petiscos ou entradas.',
    descriptionEn: 'Atlantic octopus caught in the Azores, cooked and preserved in extra virgin olive oil with garlic and bay leaf. Tender texture and intense sea flavor. Perfect for appetizers or starters.',
    price: 6.75,
    stock: 75,
    categorySlug: 'conservas',
    origin: 'Faial',
    featured: false,
    tags: ['conservas', 'polvo', 'marisco', 'atlantico'],
    imageUrl: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=800&q=80',
  },
  {
    sku: 'CON-003',
    namePt: 'Lapa dos Açores em Azeite 120g',
    nameEn: 'Azores Limpets in Olive Oil 120g',
    nameFr: 'Patelles des Açores à l\'Huile d\'Olive 120g',
    nameDe: 'Azoren Napfschnecken in Olivenöl 120g',
    descriptionPt: 'Lapas dos Açores, o marisco mais emblemático das ilhas, conservadas em azeite com alho e limão. Um petisco incontornável da gastronomia açoriana, agora disponível em conserva para apreciar em qualquer lugar.',
    descriptionEn: 'Azores limpets, the most iconic shellfish of the islands, preserved in olive oil with garlic and lemon. An unmissable appetizer of Azorean gastronomy, now available in a can to enjoy anywhere.',
    price: 7.25,
    stock: 60,
    categorySlug: 'conservas',
    origin: 'São Miguel',
    featured: true,
    tags: ['conservas', 'lapa', 'marisco', 'tipico'],
    imageUrl: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=800&q=80',
  },
  // VINHOS
  {
    sku: 'VIN-001',
    namePt: 'Vinho Branco do Pico Lajido 750ml',
    nameEn: 'Pico Lajido White Wine 750ml',
    nameFr: 'Vin Blanc du Pico Lajido 750ml',
    nameDe: 'Pico Lajido Weißwein 750ml',
    descriptionPt: 'Vinho branco produzido nas vinhas em pedra negra da Ilha do Pico, Património Mundial da UNESCO. Uva Arinto dos Açores, com notas minerais, cítricas e florais. Fresco e elegante, ideal para acompanhar peixe e marisco.',
    descriptionEn: 'White wine produced in the black stone vineyards of Pico Island, UNESCO World Heritage. Arinto dos Açores grape, with mineral, citrus and floral notes. Fresh and elegant, ideal to accompany fish and seafood.',
    price: 18.50,
    compareAtPrice: 22.00,
    stock: 30,
    categorySlug: 'vinhos',
    origin: 'Pico',
    featured: true,
    tags: ['vinho', 'branco', 'pico', 'dop', 'unesco'],
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=800&q=80',
  },
  {
    sku: 'VIN-002',
    namePt: 'Vinho Tinto Terras de Lava 750ml',
    nameEn: 'Terras de Lava Red Wine 750ml',
    nameFr: 'Vin Rouge Terras de Lava 750ml',
    nameDe: 'Terras de Lava Rotwein 750ml',
    descriptionPt: 'Vinho tinto da Ilha do Pico, produzido em solos vulcânicos de lava negra. Cor rubi intensa, aromas de frutos vermelhos e especiarias, taninos sedosos. Uma expressão única do terroir vulcânico dos Açores.',
    descriptionEn: 'Red wine from Pico Island, produced in volcanic black lava soils. Intense ruby color, aromas of red fruits and spices, silky tannins. A unique expression of the volcanic terroir of the Azores.',
    price: 21.00,
    stock: 25,
    categorySlug: 'vinhos',
    origin: 'Pico',
    featured: false,
    tags: ['vinho', 'tinto', 'pico', 'vulcanico'],
    imageUrl: 'https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=800&q=80',
  },
  {
    sku: 'VIN-003',
    namePt: 'Vinho Verdelho do Pico 750ml',
    nameEn: 'Pico Verdelho Wine 750ml',
    nameFr: 'Vin Verdelho du Pico 750ml',
    nameDe: 'Pico Verdelho Wein 750ml',
    descriptionPt: 'O Verdelho do Pico é um vinho histórico, apreciado pelas cortes europeias no século XIX. Produzido com uva Verdelho em solos de lava, apresenta cor dourada, aromas de mel, frutos tropicais e notas fumadas.',
    descriptionEn: 'Verdelho do Pico is a historic wine, appreciated by European courts in the 19th century. Produced with Verdelho grapes on lava soils, it presents a golden color, aromas of honey, tropical fruits and smoky notes.',
    price: 24.50,
    stock: 20,
    categorySlug: 'vinhos',
    origin: 'Pico',
    featured: true,
    tags: ['vinho', 'verdelho', 'pico', 'historico', 'licoroso'],
    imageUrl: 'https://images.unsplash.com/photo-1474722883778-792e7990302f?w=800&q=80',
  },
  // LICORES
  {
    sku: 'LIC-001',
    namePt: 'Licor de Maracujá do Ezequiel 700ml',
    nameEn: 'Ezequiel Passion Fruit Liqueur 700ml',
    nameFr: 'Liqueur de Fruit de la Passion Ezequiel 700ml',
    nameDe: 'Ezequiel Passionsfrucht-Likör 700ml',
    descriptionPt: 'Licor artesanal de maracujá produzido por Ezequiel na Ilha de São Miguel. Feito com maracujás frescos das ilhas, apresenta cor dourada intensa, aroma tropical e sabor doce e ácido equilibrado. Um clássico dos Açores.',
    descriptionEn: 'Artisan passion fruit liqueur produced by Ezequiel on São Miguel Island. Made with fresh island passion fruits, it has an intense golden color, tropical aroma and balanced sweet and sour flavor.',
    price: 12.50,
    stock: 45,
    categorySlug: 'licores',
    origin: 'São Miguel',
    featured: true,
    tags: ['licor', 'maracuja', 'sao-miguel', 'artesanal'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=800&q=80',
  },
  {
    sku: 'LIC-002',
    namePt: 'Licor de Ananas dos Açores 500ml',
    nameEn: 'Azores Pineapple Liqueur 500ml',
    nameFr: 'Liqueur d\'Ananas des Açores 500ml',
    nameDe: 'Azoren Ananas-Likör 500ml',
    descriptionPt: 'Licor produzido com o famoso ananás dos Açores, cultivado em estufas de pedra em São Miguel. Sabor único e intenso, cor âmbar dourada. O ananás dos Açores é considerado o mais saboroso do mundo.',
    descriptionEn: 'Liqueur made with the famous Azores pineapple, grown in stone greenhouses in São Miguel. Unique and intense flavor, golden amber color. The Azores pineapple is considered the most flavorful in the world.',
    price: 15.75,
    stock: 35,
    categorySlug: 'licores',
    origin: 'São Miguel',
    featured: true,
    tags: ['licor', 'ananas', 'sao-miguel', 'tipico'],
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=800&q=80',
  },
  // CHÁ
  {
    sku: 'CHA-001',
    namePt: 'Chá Verde Gorreana 100g',
    nameEn: 'Gorreana Green Tea 100g',
    nameFr: 'Thé Vert Gorreana 100g',
    nameDe: 'Gorreana Grüner Tee 100g',
    descriptionPt: 'Chá verde da Fábrica Gorreana, a mais antiga plantação de chá da Europa, fundada em 1883 em São Miguel. Cultivado a 400m de altitude, com clima atlântico único. Sabor suave, fresco e herbáceo, sem adição de pesticidas.',
    descriptionEn: 'Green tea from Gorreana Factory, the oldest tea plantation in Europe, founded in 1883 in São Miguel. Grown at 400m altitude, with a unique Atlantic climate. Mild, fresh and herbaceous flavor, without pesticides.',
    price: 5.25,
    stock: 90,
    categorySlug: 'cha',
    origin: 'São Miguel',
    featured: true,
    tags: ['cha', 'verde', 'gorreana', 'sao-miguel', 'europa'],
    imageUrl: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=800&q=80',
  },
  {
    sku: 'CHA-002',
    namePt: 'Chá Preto Porto Formoso 100g',
    nameEn: 'Porto Formoso Black Tea 100g',
    nameFr: 'Thé Noir Porto Formoso 100g',
    nameDe: 'Porto Formoso Schwarzer Tee 100g',
    descriptionPt: 'Chá preto da Fábrica Porto Formoso, produzido nas encostas verdejantes de São Miguel. Com mais de 150 anos de tradição, apresenta sabor robusto e encorpado, com notas terrosas e ligeiramente adstringentes.',
    descriptionEn: 'Black tea from Porto Formoso Factory, produced on the green slopes of São Miguel. With over 150 years of tradition, it has a robust and full-bodied flavor, with earthy and slightly astringent notes.',
    price: 5.75,
    stock: 85,
    categorySlug: 'cha',
    origin: 'São Miguel',
    featured: false,
    tags: ['cha', 'preto', 'porto-formoso', 'sao-miguel'],
    imageUrl: 'https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=800&q=80',
  },
  // PASTELARIA
  {
    sku: 'PAS-001',
    namePt: 'Bolos Lêvedos das Furnas Rosa Quental 400g',
    nameEn: 'Furnas Lêvedos Cakes Rosa Quental 400g',
    nameFr: 'Gâteaux Lêvedos des Furnas Rosa Quental 400g',
    nameDe: 'Furnas Lêvedos Kuchen Rosa Quental 400g',
    descriptionPt: 'Os autênticos Bolos Lêvedos das Furnas, produzidos pela Rosa Quental segundo a receita original. Feitos com farinha, ovos, açúcar e manteiga, são pequenos, redondos e com textura única. Especialidade de São Miguel.',
    descriptionEn: 'The authentic Furnas Lêvedos Cakes, produced by Rosa Quental according to the original recipe. Made with flour, eggs, sugar and butter, they are small, round and with a unique texture. São Miguel specialty.',
    price: 6.85,
    stock: 60,
    categorySlug: 'pastelaria',
    origin: 'São Miguel',
    featured: true,
    tags: ['bolos', 'levedos', 'furnas', 'sao-miguel', 'mais_vendido'],
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80',
  },
  {
    sku: 'PAS-002',
    namePt: 'Queijadas de Vila Franca do Campo 12 unid.',
    nameEn: 'Vila Franca do Campo Cheesecakes 12 units',
    nameFr: 'Queijadas de Vila Franca do Campo 12 unités',
    nameDe: 'Vila Franca do Campo Käsekuchen 12 Stück',
    descriptionPt: 'Queijadas tradicionais de Vila Franca do Campo, doce típico de São Miguel feito com queijo fresco, ovos, açúcar e canela. Pequenas, doces e irresistíveis, são um dos doces mais apreciados dos Açores.',
    descriptionEn: 'Traditional queijadas from Vila Franca do Campo, a typical sweet from São Miguel made with fresh cheese, eggs, sugar and cinnamon. Small, sweet and irresistible, they are one of the most appreciated sweets of the Azores.',
    price: 11.50,
    stock: 40,
    categorySlug: 'pastelaria',
    origin: 'São Miguel',
    featured: true,
    tags: ['queijadas', 'doces', 'sao-miguel', 'mais_vendido'],
    imageUrl: 'https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81?w=800&q=80',
  },
  {
    sku: 'PAS-003',
    namePt: 'Dona Amélia Original 6 unid. Terceira',
    nameEn: 'Original Dona Amélia 6 units Terceira',
    nameFr: 'Dona Amélia Original 6 unités Terceira',
    nameDe: 'Original Dona Amélia 6 Stück Terceira',
    descriptionPt: 'A Dona Amélia é o doce mais famoso da Ilha Terceira, criado em 1907 em homenagem à Rainha D. Amélia. Feito com mel de cana, amêndoa, canela e especiarias, é um doce único e inconfundível.',
    descriptionEn: 'Dona Amélia is the most famous sweet from Terceira Island, created in 1907 in honor of Queen D. Amélia. Made with cane honey, almonds, cinnamon and spices, it is a unique and unmistakable sweet.',
    price: 8.50,
    stock: 55,
    categorySlug: 'pastelaria',
    origin: 'Terceira',
    featured: true,
    tags: ['doces', 'dona-amelia', 'terceira', 'historico'],
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80',
  },
  // COMPOTAS & MEL
  {
    sku: 'COM-001',
    namePt: 'Compota de Maracujá dos Açores 280g',
    nameEn: 'Azores Passion Fruit Jam 280g',
    nameFr: 'Confiture de Fruit de la Passion des Açores 280g',
    nameDe: 'Azoren Passionsfrucht-Marmelade 280g',
    descriptionPt: 'Compota artesanal de maracujá produzida com fruta fresca dos Açores. Sem conservantes artificiais, com pedaços de fruta e sabor intenso. Ideal para barrar em torradas ou acompanhar queijos.',
    descriptionEn: 'Artisan passion fruit jam made with fresh Azores fruit. Without artificial preservatives, with fruit pieces and intense flavor. Ideal for spreading on toast or accompanying cheeses.',
    price: 4.75,
    stock: 70,
    categorySlug: 'compotas',
    origin: 'São Miguel',
    featured: false,
    tags: ['compota', 'maracuja', 'artesanal', 'sao-miguel'],
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80',
  },
  {
    sku: 'COM-002',
    namePt: 'Mel dos Açores Puro 500g',
    nameEn: 'Pure Azores Honey 500g',
    nameFr: 'Miel Pur des Açores 500g',
    nameDe: 'Reiner Azoren Honig 500g',
    descriptionPt: 'Mel puro produzido por abelhas nas ilhas dos Açores, onde a flora endémica e o clima atlântico criam um néctar único. Rico em antioxidantes, com sabor floral e textura cremosa. Sem adição de açúcar.',
    descriptionEn: 'Pure honey produced by bees on the Azores islands, where endemic flora and Atlantic climate create a unique nectar. Rich in antioxidants, with floral flavor and creamy texture. No added sugar.',
    price: 8.25,
    stock: 45,
    categorySlug: 'compotas',
    origin: 'Flores',
    featured: false,
    tags: ['mel', 'puro', 'flores', 'artesanal'],
    imageUrl: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&q=80',
  },
  // PIMENTAS
  {
    sku: 'PIM-001',
    namePt: 'Pimenta da Terra Dona Pimentinha 370g',
    nameEn: 'Dona Pimentinha Earth Pepper 370g',
    nameFr: 'Piment de la Terre Dona Pimentinha 370g',
    nameDe: 'Dona Pimentinha Erdpfeffer 370g',
    descriptionPt: 'A Pimenta da Terra é o condimento mais característico da cozinha açoriana. Produzida pela Dona Pimentinha em São Miguel, esta pasta de pimenta vermelha é essencial em pratos como alcatra, carne guisada e sopas.',
    descriptionEn: 'Pimenta da Terra is the most characteristic condiment of Azorean cuisine. Produced by Dona Pimentinha in São Miguel, this red pepper paste is essential in dishes like alcatra, stewed meat and soups.',
    price: 3.25,
    stock: 120,
    categorySlug: 'pimentas',
    origin: 'São Miguel',
    featured: true,
    tags: ['pimenta', 'condimento', 'sao-miguel', 'mais_vendido', 'tipico'],
    imageUrl: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=800&q=80',
  },
  {
    sku: 'PIM-002',
    namePt: 'Molho Picante de Pimenta dos Açores 200ml',
    nameEn: 'Azores Hot Pepper Sauce 200ml',
    nameFr: 'Sauce Piquante au Poivre des Açores 200ml',
    nameDe: 'Azoren Scharfe Pfeffersauce 200ml',
    descriptionPt: 'Molho picante artesanal produzido com pimentas frescas dos Açores, vinagre e especiarias. Intensidade média-alta, ideal para acompanhar grelhados, hambúrgueres ou adicionar a marinadas.',
    descriptionEn: 'Artisan hot sauce made with fresh Azores peppers, vinegar and spices. Medium-high intensity, ideal to accompany grills, burgers or add to marinades.',
    price: 4.50,
    stock: 65,
    categorySlug: 'pimentas',
    origin: 'São Miguel',
    featured: false,
    tags: ['pimenta', 'molho', 'picante', 'artesanal'],
    imageUrl: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&q=80',
  },
  // BEBIDAS
  {
    sku: 'BEB-001',
    namePt: 'Cerveja Melo Abreu Açores 330ml (Pack 6)',
    nameEn: 'Melo Abreu Azores Beer 330ml (Pack 6)',
    nameFr: 'Bière Melo Abreu Açores 330ml (Pack 6)',
    nameDe: 'Melo Abreu Azoren Bier 330ml (6er Pack)',
    descriptionPt: 'Cerveja artesanal produzida nos Açores pela Fábrica de Cervejas João Melo Abreu. Lager suave e refrescante, com malte e lúpulo selecionados. O sabor autêntico das ilhas em cada gole.',
    descriptionEn: 'Craft beer produced in the Azores by João Melo Abreu Brewery. Smooth and refreshing lager, with selected malt and hops. The authentic taste of the islands in every sip.',
    price: 9.50,
    stock: 40,
    categorySlug: 'bebidas',
    origin: 'São Miguel',
    featured: false,
    tags: ['cerveja', 'artesanal', 'sao-miguel', 'bebidas'],
    imageUrl: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?w=800&q=80',
  },
  // CHARCUTARIA
  {
    sku: 'CHA-CH-001',
    namePt: 'Chouriço de Carne dos Açores 300g',
    nameEn: 'Azores Meat Sausage 300g',
    nameFr: 'Chorizo de Viande des Açores 300g',
    nameDe: 'Azoren Fleischwurst 300g',
    descriptionPt: 'Chouriço artesanal produzido com carne de porco dos Açores, temperado com pimenta da terra, alho e especiarias tradicionais. Fumado lentamente em madeira de carvalho. Sabor intenso e autêntico.',
    descriptionEn: 'Artisan sausage made with Azores pork, seasoned with local pepper, garlic and traditional spices. Slowly smoked in oak wood. Intense and authentic flavor.',
    price: 7.85,
    stock: 35,
    categorySlug: 'charcutaria',
    origin: 'Terceira',
    featured: false,
    tags: ['charcutaria', 'chourico', 'terceira', 'artesanal'],
    imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&q=80',
  },
  // OUTROS
  {
    sku: 'OUT-001',
    namePt: 'Cabaz Gourmet Açores — Seleção Premium',
    nameEn: 'Azores Gourmet Hamper — Premium Selection',
    nameFr: 'Panier Gourmet Açores — Sélection Premium',
    nameDe: 'Azoren Gourmet-Korb — Premium-Auswahl',
    descriptionPt: 'Cabaz gourmet com uma seleção dos melhores produtos dos Açores: queijo São Jorge DOP, manteiga, conservas, chá Gorreana, pimenta da terra e licor de maracujá. A oferta perfeita para quem aprecia o melhor das ilhas.',
    descriptionEn: 'Gourmet hamper with a selection of the best Azores products: São Jorge DOP cheese, butter, preserves, Gorreana tea, local pepper and passion fruit liqueur. The perfect gift for those who appreciate the best of the islands.',
    price: 65.00,
    compareAtPrice: 78.00,
    stock: 15,
    categorySlug: 'outros',
    origin: 'Açores',
    featured: true,
    tags: ['cabaz', 'gourmet', 'oferta', 'premium', 'mais_vendido'],
    imageUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80',
  },
]

export async function POST() {
  try {
    // Delete existing data (order matters due to foreign keys)
    await db.product.deleteMany()
    await db.category.deleteMany()

    // Create categories and store their IDs in a slug map
    const categoryMap: Record<string, string> = {}
    for (const cat of CATEGORIES) {
      const created = await db.category.create({
        data: {
          slug: cat.slug,
          namePt: cat.namePt,
          nameEn: cat.nameEn,
          nameFr: cat.nameFr,
          nameDe: cat.nameDe,
          sortOrder: cat.sortOrder,
        },
      })
      categoryMap[cat.slug] = created.id
    }

    // Create products one by one
    const createdProducts = []
    for (const p of PRODUCTS) {
      const categoryId = categoryMap[p.categorySlug] || null
      const product = await db.product.create({
        data: {
          sku: p.sku,
          namePt: p.namePt,
          nameEn: p.nameEn,
          nameFr: p.nameFr,
          nameDe: p.nameDe,
          descriptionPt: p.descriptionPt,
          descriptionEn: p.descriptionEn,
          price: p.price,
          compareAtPrice: p.compareAtPrice || null,
          currency: 'EUR',
          stockQuantity: p.stock,
          categoryId,
          imageUrl: p.imageUrl,
          images: JSON.stringify([p.imageUrl]),
          origin: p.origin,
          featured: p.featured,
          tags: JSON.stringify(p.tags),
          isActive: true,
        },
      })
      createdProducts.push(product)
    }

    return NextResponse.json({
      message: `Seeded ${Object.keys(categoryMap).length} categories and ${createdProducts.length} products`,
      categoriesCount: Object.keys(categoryMap).length,
      productsCount: createdProducts.length,
    })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({ error: 'Seed failed' }, { status: 500 })
  }
}
